{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.mandarin",
    "module": "discord-ipc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "discord-ipc-1.0.jar",
          "url": "discord-ipc-1.0.jar",
          "size": 29901,
          "sha512": "8d5b89e38046857dfecc698ff4fe50ae4fe931fb98f64770e9d118e947093d546551b4d84daf6e55d6f65161c08b96d7f5ff3e8406638b5644d7418f9b6a5c09",
          "sha256": "1e14d27f0d89f857364352203372e68e91611725bce9ea8f6ffd1275c55a8215",
          "sha1": "d2b8dcd955b1bba48d0deda8973c4b971c560045",
          "md5": "c2609804a556e04f89699f780754874e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-ipc-1.0.jar",
          "url": "discord-ipc-1.0.jar",
          "size": 29901,
          "sha512": "8d5b89e38046857dfecc698ff4fe50ae4fe931fb98f64770e9d118e947093d546551b4d84daf6e55d6f65161c08b96d7f5ff3e8406638b5644d7418f9b6a5c09",
          "sha256": "1e14d27f0d89f857364352203372e68e91611725bce9ea8f6ffd1275c55a8215",
          "sha1": "d2b8dcd955b1bba48d0deda8973c4b971c560045",
          "md5": "c2609804a556e04f89699f780754874e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-ipc-1.0-sources.jar",
          "url": "discord-ipc-1.0-sources.jar",
          "size": 15013,
          "sha512": "3705660f88887cbb71fd4cf5a8cd5b49095087436485445fd83d7212b91fb016172b8822c5b3e7edc352cbbf3e9dba7e2c07664ea034d38f94e3b133ce69b939",
          "sha256": "3e17b87e96c8bad021b02ab03a604bc99ceec2c46aa4115e96dda8bac76c03ba",
          "sha1": "45f437021f456ada5d758b2f4eddacc9ca5e87da",
          "md5": "96078bfd1b6017665b7226996d907e20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-ipc-1.0-javadoc.jar",
          "url": "discord-ipc-1.0-javadoc.jar",
          "size": 177366,
          "sha512": "05ff395e5e814cce163d19bc0f50713094dc09ac0ba7d7f560c114a4949ae11c65185e5e0fd8c91430048850f9f97a9ffcc781147bc229eb6576d3c2d5cef9b4",
          "sha256": "e72044a279cc31f499464c814206cfe4ee43d004c22d68a01ebcfea45c51642a",
          "sha1": "4c85fdeb9d596551f8ac36bd3c1d92b54a5b41be",
          "md5": "beb4a71404582c6e88c0909283f1ccef"
        }
      ]
    }
  ]
}
