{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.mandarin",
    "module": "discord-ipc",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "discord-ipc-1.0.jar",
          "url": "discord-ipc-1.0.jar",
          "size": 30594,
          "sha512": "3c90bc4d39697fbdb7d36559dde2f6dae8aa2394c842ca9c576a87192f323543ded91e3ab02979a488f912a461ce5ad29f7da00f72b465c8a938841d7602c0e4",
          "sha256": "7f187eda3d06aab5ad75364632af0f3a076802cde9ab1a5c9e52c779f491ca8d",
          "sha1": "39bd4487151de21f3627b1386af8903fc6e0d266",
          "md5": "779bd229a43aee9e6e336588b9b9af00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-ipc-1.0.jar",
          "url": "discord-ipc-1.0.jar",
          "size": 30594,
          "sha512": "3c90bc4d39697fbdb7d36559dde2f6dae8aa2394c842ca9c576a87192f323543ded91e3ab02979a488f912a461ce5ad29f7da00f72b465c8a938841d7602c0e4",
          "sha256": "7f187eda3d06aab5ad75364632af0f3a076802cde9ab1a5c9e52c779f491ca8d",
          "sha1": "39bd4487151de21f3627b1386af8903fc6e0d266",
          "md5": "779bd229a43aee9e6e336588b9b9af00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-ipc-1.0-sources.jar",
          "url": "discord-ipc-1.0-sources.jar",
          "size": 15013,
          "sha512": "876362efc94301f9fe06bd182496a9de85f62441ef011b68f4b84020825e98216fa6fe70be1ea8a4e9b209b2bba9f9ca7aaa7476b38c2a824616030b9bde94bb",
          "sha256": "b330fa33d94b931ba37377deef1f782df4387740f64f348afefd439a1a6d0115",
          "sha1": "ea901cc1beb0a728d6f2ada1857cedf5ef44dc2a",
          "md5": "8c8aaa17e26e654ce324d0fedd7d6f6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-ipc-1.0-javadoc.jar",
          "url": "discord-ipc-1.0-javadoc.jar",
          "size": 203926,
          "sha512": "1fab554c2395962f7991602e66e5d86edaafa2471517fc216424f44f6f5ac006ff9afa063cd7c6577e2e8d9391551e9d7a49fdf1d6014acb7ab5554c3e9464f5",
          "sha256": "6058afbc626e0eed6c237349a31c0249c7e7d843bd2e73a66edea36c586cd0ab",
          "sha1": "d1070ddcdad048b8462bcc2d543081754c3bea31",
          "md5": "b49c289ac0c82cf7ed7fe0144ed629a6"
        }
      ]
    }
  ]
}
